POST http://localhost:3001/api/persons
Content-Type: application/json

{    
      "name": "Art Hellas"
}


### test for existing person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
      "name":"Arto Vinhavaine",
      "number":89989
}

###
POST http://localhost:3001/api/persons
Content-Type:application/json

{    
     "name": "Ada Lovelace", 
      "number": "39-44-88832458"
}
### test for new person
POST http://localhost:3001/api/persons
Content-Type:application/json

{    
     "name": "Xinxin Zhg", 
      "number": "39-44-5323"
}


###
POST http://localhost:3001/api/persons
Content-Type:application/json

{     
 "number": "39-44-5323544423"
}